const { withMainActivity } = require('expo/config-plugins');

/**
 * Cap the app's window at a refresh rate (60 Hz by default) on Android.
 *
 * Budget phones with 120 Hz panels (Redmi 14C, 2026-10-01: hot after minutes of ordinary
 * use on the newest build) draw every frame twice as often as a 60 Hz phone, on a chip that
 * is not faster. React Native renders at whatever the display runs, and scrolling a list at
 * 120 fps on a Helio G81 is sustained CPU + GPU work for no benefit the eye notices in an
 * attendance app. Games do the same thing through this exact API.
 *
 * Two mechanisms, because OEM skins honour them differently:
 *  - `preferredDisplayModeId` (API 23+): the display mode with the window's own resolution
 *    whose refresh rate is the highest at or below the cap. MIUI respects it.
 *  - `preferredMaxDisplayRefreshRate` (API 31+): the newer, resolution-independent form.
 * A phone whose only mode is 60 Hz, or that ignores both, is simply unchanged. The user's
 * own "Force peak refresh rate" developer option overrides the app, as it should.
 *
 * Injected into MainActivity.onCreate because `android/` is regenerated by prebuild on
 * every CI build. Idempotent; a marker comment guards the insert.
 */
const MARKER = '// drosspot: refresh-rate cap';

function kotlinSnippet(maxHz) {
  return `
    ${MARKER} (plugins/withAndroidRefreshRateCap.js)
    try {
      val cap = ${Number(maxHz).toFixed(1)}f
      val display = if (android.os.Build.VERSION.SDK_INT >= 30) this.display else @Suppress("DEPRECATION") windowManager.defaultDisplay
      if (display != null && android.os.Build.VERSION.SDK_INT >= 23) {
        val current = display.mode
        var best: android.view.Display.Mode? = null
        for (m in display.supportedModes) {
          if (m.physicalWidth != current.physicalWidth || m.physicalHeight != current.physicalHeight) continue
          if (m.refreshRate > cap + 0.5f) continue
          if (best == null || m.refreshRate > best.refreshRate) best = m
        }
        val params = window.attributes
        if (best != null) params.preferredDisplayModeId = best.modeId
        if (android.os.Build.VERSION.SDK_INT >= 31) params.preferredMaxDisplayRefreshRate = cap
        window.attributes = params
      }
    } catch (e: Throwable) {
      // Never let a display quirk stop the app from starting.
    }
`;
}

/** Pure transform, exported for the test. Kotlin MainActivity only (the SDK 54 template). */
function inject(contents, maxHz = 60) {
  if (contents.includes(MARKER)) return contents;
  // The template's onCreate starts with `super.onCreate(null)` (Expo) — insert right after it.
  const re = /(override fun onCreate\(savedInstanceState: Bundle\?\) \{[^\n]*\n(?:[^\n]*\n)*?\s*super\.onCreate\([^)]*\)\n)/;
  if (!re.test(contents)) {
    throw new Error('withAndroidRefreshRateCap: MainActivity.onCreate not found — the template changed; update the plugin.');
  }

  return contents.replace(re, `$1${kotlinSnippet(maxHz)}`);
}

module.exports = function withAndroidRefreshRateCap(config, { maxHz = 60 } = {}) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error('withAndroidRefreshRateCap expects a Kotlin MainActivity.');
    }
    cfg.modResults.contents = inject(cfg.modResults.contents, maxHz);
    return cfg;
  });
};
module.exports.inject = inject;
module.exports.MARKER = MARKER;
