export const colors = {
  primary: '#208AEF',
  primaryLight: '#E8F4FD',
  primaryDark: '#1A6FBF',
  secondary: '#6B7280',
  success: '#065F46',
  successLight: '#D1FAE5',
  warning: '#92400E',
  warningLight: '#FEF3C7',
  danger: '#991B1B',
  dangerLight: '#FEE2E2',
  info: '#1E40AF',
  infoLight: '#DBEAFE',
  white: '#FFFFFF',
  background: '#F9FAFB',
  surface: '#FFFFFF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  textTertiary: '#9CA3AF',
  textInverse: '#FFFFFF',
  overlay: 'rgba(0,0,0,0.5)',
  whatsapp: '#25D366',
} as const;

export type ColorKey = keyof typeof colors;
